In [2]:
#  --- Classification Models ---

#  Using
#     sklearn
#     statsmodel


In [22]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression

# in sklearn model
# There are 3 steps :
#     * Classification object creation
#     * Fit object with x,y values
#     * Predict using trained data classification model

In [4]:
# classification object creation
clfs_lrs = LogisticRegression()

In [5]:
df = pd.read_csv('House_Price.csv')
df.head()

price  resid_area  air_qual  room_num   age  dist1  dist2  dist3  dist4  \
0   24.0       32.31     0.538     6.575  65.2   4.35   3.81   4.18   4.01   
1   21.6       37.07     0.469     6.421  78.9   4.99   4.70   5.12   5.06   
2   34.7       37.07     0.469     7.185  61.1   5.03   4.86   5.01   4.97   
3   33.4       32.18     0.458     6.998  45.8   6.21   5.93   6.16   5.96   
4   36.2       32.18     0.458     7.147  54.2   6.16   5.86   6.37   5.86   

   teachers  poor_prop airport  n_hos_beds  n_hot_rooms waterbody  rainfall  \
0      24.7       4.98     YES       5.480      11.1920     River        23   
1      22.2       9.14      NO       7.332      12.1728      Lake        42   
2      22.2       4.03      NO       7.394     101.1200      None        38   
3      21.3       2.94     YES       9.268      11.2672      Lake        45   
4      21.3       5.33      NO       8.824      11.2896      Lake        55   

  bus_ter     parks  Sold  
0     YES  0.049347     0  
1     YES  0.046146     1  
2     YES  0.045764     0  
3     YES  0.047151     0  
4     YES  0.039474     0

In [6]:
#  ----------------------------------------------------------
#  x, y are independent and dependant variables respectively
#  and independent variables will always be 2 dimensional
#  ----------------------------------------------------------

In [7]:
x = df[['price']]
y = df['Sold']

In [8]:
#  fit x,y to clfs_lrs object which is trained using LogisticRegression()

clfs_lrs.fit(x,y)

LogisticRegression()

In [9]:
#  now we need to find beta1 and beta0 (probaility)

In [10]:
# for beta0
clfs_lrs.coef_

array([[-0.03571865]])

In [11]:
# for beta1
clfs_lrs.intercept_

array([0.61477516])

In [18]:
# --------------------------------------------------
#  multiple predictor using sklearn

In [19]:
# Regression model only use numerical values for training
# before that we need to solve outliers and missing values

In [21]:
df.describe()

price  resid_area    air_qual    room_num         age       dist1  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    22.528854   41.136779    0.554695    6.284634   68.574901    3.971996   
std      9.182176    6.860353    0.115878    0.702617   28.148861    2.108532   
min      5.000000   30.460000    0.385000    3.561000    2.900000    1.130000   
25%     17.025000   35.190000    0.449000    5.885500   45.025000    2.270000   
50%     21.200000   39.690000    0.538000    6.208500   77.500000    3.385000   
75%     25.000000   48.100000    0.624000    6.623500   94.075000    5.367500   
max     50.000000   57.740000    0.871000    8.780000  100.000000   12.320000   

            dist2       dist3       dist4    teachers   poor_prop  n_hos_beds  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  498.000000   
mean     3.628775    3.960672    3.618972   21.544466   12.653063    7.899767   
std      2.108580    2.119797    2.099203    2.164946    7.141062    1.476683   
min      0.920000    1.150000    0.730000   18.000000    1.730000    5.268000   
25%      1.940000    2.232500    1.940000   19.800000    6.950000    6.634500   
50%      3.010000    3.375000    3.070000   20.950000   11.360000    7.999000   
75%      4.992500    5.407500    4.985000   22.600000   16.955000    9.088000   
max     11.930000   12.320000   11.940000   27.400000   37.970000   10.876000   

       n_hot_rooms    rainfall       parks        Sold  
count   506.000000  506.000000  506.000000  506.000000  
mean     13.041605   39.181818    0.054454    0.454545  
std       5.238957   12.513697    0.010632    0.498422  
min      10.057600    3.000000    0.033292    0.000000  
25%      11.189800   28.000000    0.046464    0.000000  
50%      12.720000   39.000000    0.053507    0.000000  
75%      14.170800   50.000000    0.061397    1.000000  
max     101.120000   60.000000    0.086711    1.000000

In [23]:
# outlier in n_hot_rooms
np.percentile(df.n_hot_rooms,[99][0])

15.39952

In [24]:
upper_v = np.percentile(df.n_hot_rooms,[99][0])

In [27]:
df.n_hot_rooms[(df.n_hot_rooms > 3 * upper_v)] = 3 * upper_v

/tmp/ipykernel_4697/1891868419.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.n_hot_rooms[(df.n_hot_rooms > 3 * upper_v)] = 3 * upper_v


In [28]:
# outlier in rainfall
np.percentile(df.rainfall,[1][0])

20.0

In [29]:
lower_v = np.percentile(df.rainfall,[1][0])

In [30]:
df.rainfall[(df.rainfall < 0.3 * lower_v)] = 0.3 * lower_v

/tmp/ipykernel_4697/3706604571.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rainfall[(df.rainfall < 0.3 * lower_v)] = 0.3 * lower_v


In [34]:
# missing values in n_hos_beds
df.n_hos_beds = df.n_hos_beds.fillna(df.n_hos_beds.mean())

In [36]:
df['Avg_dist'] = (df.dist1 + df.dist2 + df.dist3 + df.dist4)/4

In [37]:
del df['dist1']
del df['dist2']
del df['dist3']
del df['dist4']

In [42]:
# use dummy variables to replace non-numerical values
df = pd.get_dummies(df)

In [45]:
df.head()

price  resid_area  air_qual  room_num   age  teachers  poor_prop  \
0   24.0       32.31     0.538     6.575  65.2      24.7       4.98   
1   21.6       37.07     0.469     6.421  78.9      22.2       9.14   
2   34.7       37.07     0.469     7.185  61.1      22.2       4.03   
3   33.4       32.18     0.458     6.998  45.8      21.3       2.94   
4   36.2       32.18     0.458     7.147  54.2      21.3       5.33   

   n_hos_beds  n_hot_rooms  rainfall     parks  Sold  Avg_dist  airport_YES  \
0       5.480     11.19200        23  0.049347     0    4.0875            1   
1       7.332     12.17280        42  0.046146     1    4.9675            0   
2       7.394     46.19856        38  0.045764     0    4.9675            0   
3       9.268     11.26720        45  0.047151     0    6.0650            1   
4       8.824     11.28960        55  0.039474     0    6.0625            0   

   waterbody_Lake  waterbody_Lake and River  waterbody_River  bus_ter_YES  
0               0                         0                1            1  
1               1                         0                0            1  
2               0                         0                0            1  
3               1                         0                0            1  
4               1                         0                0            1

In [46]:
#  assign all the variable to x using loc

x = df.loc[:, df.columns != 'Sold']

In [48]:
y = df.Sold

In [49]:
clfs_lrs.fit(x,y)

/home/zoro/Intern/intern/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [50]:
clfs_lrs.coef_

array([[-0.24707146, -0.01673301, -0.17112593,  0.85535793, -0.00618161,
         0.24317462, -0.21030858,  0.158649  , -0.09360917, -0.00642256,
        -0.00818041, -0.33272922, -0.1339214 , -0.05592356, -0.01413927,
         0.16859518,  0.00140717]])

In [51]:
clfs_lrs.intercept_

array([0.00341868])

In [54]:
# ----------------------------------------------------
# ----------------- Confusion Matrix -----------------

#  there are two type error in Confusion matrix

#         Type I error - false positive
#         Type II error - false negative


In [57]:
#  generally 0.5 is used for prediction normally
    
#     > 0.5 = 1 (True)
#     < 0.5 = 0 (False)
    
clfs_lrs.predict_proba(x)

array([[0.12231815, 0.87768185],
       [0.37914944, 0.62085056],
       [0.98199511, 0.01800489],
       ...,
       [0.27971295, 0.72028705],
       [0.29029636, 0.70970364],
       [0.17423676, 0.82576324]])

In [58]:
y_predict = clfs_lrs.predict(x)
y_predict

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,

In [59]:
# if we want to use 0.3 for prediction we have to assign it

y_predict_03 = (clfs_lrs.predict_proba(x)[:1] >= 0.3).astype(bool)

In [60]:
# for creating confusion matrix 
from sklearn.metrics import confusion_matrix

In [61]:
confusion_matrix(y, y_predict)

array([[197,  79],
       [ 78, 152]])